In [2]:
import torch

In [18]:
x = torch.empty(3,2,4)
print(x)

tensor([[[-2.4798e-38,  1.0846e-42,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])


In [19]:
torch.randn(3,2,4)

tensor([[[-0.2358, -1.0703,  0.6452,  0.7998],
         [ 0.8408,  0.5067,  1.0570,  2.0320]],

        [[-0.5646, -1.4783, -0.2903, -1.8997],
         [-1.2783, -1.4226, -1.0840,  0.6212]],

        [[ 0.1185,  2.2722, -1.3729, -0.2887],
         [ 1.4926,  0.2723, -1.4336,  0.9688]]])

In [20]:
torch.rand(3,2,4)

tensor([[[0.7577, 0.9846, 0.7364, 0.2689],
         [0.5211, 0.6641, 0.4857, 0.7346]],

        [[0.3810, 0.0621, 0.2006, 0.5028],
         [0.1878, 0.1291, 0.0332, 0.1495]],

        [[0.7913, 0.3627, 0.3996, 0.5819],
         [0.6448, 0.0817, 0.5545, 0.4636]]])

In [21]:
torch.zeros(2,4,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [22]:
torch.ones(2,1,3)

tensor([[[1., 1., 1.]],

        [[1., 1., 1.]]])

In [31]:
a =  torch.tensor([2,8,2])
b = torch.tensor([2,3,2])
print(a)
print(b)
print(torch.add(a,b))

tensor([2, 8, 2])
tensor([2, 3, 2])
tensor([ 4, 11,  4])


In [44]:
x = torch.randn(4,3)
print(x)
print('---------------------')
print(x[:3, 2])

tensor([[-0.5298, -1.6012, -0.3057],
        [-0.0274,  0.7925, -0.2324],
        [-1.6789, -0.7289, -0.1169],
        [ 0.2636, -1.3235, -0.2764]])
---------------------
tensor([-0.3057, -0.2324, -0.1169])


In [50]:
y = x.view(4, 3)
print(y)

tensor([[-0.5298, -1.6012, -0.3057],
        [-0.0274,  0.7925, -0.2324],
        [-1.6789, -0.7289, -0.1169],
        [ 0.2636, -1.3235, -0.2764]])


In [59]:
s=torch.ones(5)
print(s)

tensor([1., 1., 1., 1., 1.])


In [60]:
#y.ndim
s.ndim

1